excluded:
  - Test

analyzer_rules:
  - unused_import
  - unused_declaration

disabled_rules:
  - trailing_whitespace
  - compiler_protocol_init
  - function_parameter_count
  - multiple_closures_with_trailing_closure
  - cyclomatic_complexity
  - file_length
  - syntactic_sugar
  - unused_capture_list
  - blanket_disable_command
  - identifier_name
  - trailing_comma

opt_in_rules:
  - vertical_parameter_alignment_on_call
  - empty_count

# configurable rules can be customized from this configuration file
force_cast: warning
opening_brace: error
closing_brace: error
colon:
  severity: error
comma: error
empty_enum_arguments: error
function_body_length:
  warning: 600
  error: 600
type_body_length:
  warning: 600
  error: 600
line_length:
  warning: 180
  error: 180
  ignores_comments: true
return_arrow_whitespace: error
statement_position:
  severity: error
trailing_semicolon: error
vertical_parameter_alignment: error
vertical_parameter_alignment_on_call:
  severity: error
